jobs:
    include:
        - os: linux
          dist: focal
          env: QT_REPO=ppa:beineri/opt-qt-5.15.2-focal QT_PREFIX=515 SNAPSHOT=0
        - os: linux
          dist: focal
          env: QT_REPO=ppa:beineri/opt-qt-5.15.2-focal QT_PREFIX=515 SNAPSHOT=1
        - os: osx
          osx_image: xcode11.3
        - os: windows
          before_install:
            - choco install python --version 3.8.0
            - python -m pip install --upgrade pip
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
git:
    depth: 9999999
    autocrlf: input
language: sh

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-install.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-install.sh;   fi
    - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then  powershell -executionpolicy bypass -file ci\\travis-windows-install.ps1;   fi
    - pip3 install cloudsmith-cli

script:
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./ci/travis-linux-script.sh; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./ci/travis-osx-script.sh;   fi
    - if [ "${TRAVIS_OS_NAME}" = "windows" ]; then  powershell -executionpolicy bypass -file ci\\travis-windows-script.ps1;   fi

# Note: API key variable CLOUDSMITH_API_KEY must be present in Travis settings.
deploy:
    skip_cleanup: true
    on:
        branch:
            - ci-test
            - master
            - migrate-bintray-to-cloudsmith
        condition: $TRAVIS_OS_NAME != linux
    provider: script
    script: bash -x build/upload-artifacts.sh
